version: '2'
services: 
    mysql: 
        environment: 
            MYSQL_ROOT_PASSWORD: "123456"
        image: "docker.io/mysql:5.6"
        volumes: 
            - "./mysql/init:/docker-entrypoint-initdb.d"
        ports:
            - "3306:3306"